version: '3.5'

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: blog_piligrim
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  mainapp:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql://user:password@pg:5432/blog_piligrim'
      CONFIG_NAME: 'DevConfig'
    volumes:
    - ./blog_piligrim:/mainapp/blog_piligrim
    ports:
      - 5000:5000
    depends_on:
      - pg